---
galaxy_info:
  author: Luis Hdez
  description: ~
  company: wobblecode
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: MacOSX
    versions:
    - 10.9
    - 10.10
    - 10.11
  categories:
    - development
    - packaging
dependencies:
- osxc.packages
