---
default_brew_taps:
  - caskroom/fonts
  - thoughtbot/formulae
default_rew_packages:
  - zsh
  - the_silver_searcher # Command line searcher
  - pick # Fuzzy finder command line tool to select options
  - asciinema # Record terminal sessions to asciinema.org
  - youtube-dl # media youtube downloader
  - ffmpeg # media converter
  - libav # media codecs
  - lame # media codecs
  - flac # media codecs
default_cask_packages:
  - font-inconsolata
  - font-source-code-pro
